"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var MEMBER_ROLE;
(function (MEMBER_ROLE) {
    MEMBER_ROLE["ADMIN"] = "admin";
    MEMBER_ROLE["MODERATOR"] = "moderator";
    MEMBER_ROLE["GUEST"] = "guest";
})(MEMBER_ROLE || (MEMBER_ROLE = {}));
var memberRole = MEMBER_ROLE.GUEST;
console.log(memberRole);
var zero = 0 /* ZERO_ONE.ZERO */;
console.log(zero);
var one = 1 /* ZERO_ONE.ONE */;
console.log(one);
var two = 2 /* TWO_THREE.TWO */;
console.log(two);
var three = 3 /* TWO_THREE.THREE */;
console.log(three);
var oneHundred = 100 /* HUNDREDS.ONE */;
console.log(oneHundred);
